### ISSUE TITLE
Documentation and Commenting

### ISSUE THREAD

**Issue by 3x071c** [3x071c/lsg-remix#160]
Large parts of the codebase remain largely undocumented, and uncommented. We need a central reference (Markdown docs) about design decisions and why they were taken, collected knowledge and implementation details. Comments should be thorough, easy to approach and detail every part of a components/scripts lifecycle, usage and most importantly, the **why** (not the how). Ideally, they should use a uniform convention (f.e. [JSDoc Syntax](https://jsdoc.app) for descriptions) and literal (`/** <content> */`).

**Comment by simonwkla** [comment]
Could you provide us with an example how a documented file could/should look like? Would be awesome!

**Comment by 3x071c** [comment]
Closed in #174
