### ISSUE TITLE
Custom Image component doesnt work with Box Shadows

### ISSUE THREAD

**Issue by simonwkla** [3x071c/lsg-remix#23]
The Custom Image Component that attempts to unify `NextImage` and `ChakraImage` doesnt seem to work with box shadows (I tried to fix this bug for several hours..) 
To Reproduce try the following:

```js
<Box boxShadow="lg">
      <Image
          src={backgroundImage}
          alt="text.."
          priority
	/>
</Box>
```

You will see a small white (or gray depending on the color scheme) area below the image that is not intended

**Comment by 3x071c** [comment]
Why not give the Image a box shadow directly?

**Comment by simonwkla** [comment]
This didnt work. Maybe i did something wrong

**Comment by simonwkla** [comment]
This can be fixed by adding a `d:"flex"` property on the Box:
```js
<Box boxShadow="lg" d="flex">
      <Image
          src={backgroundImage}
          alt="text.."
          priority
	/>
</Box>
```
