### ISSUE TITLE
Pizza ordering page (lab)

### ISSUE THREAD

**Issue by 3x071c** [3x071c/lsg-remix#256]
We used to have a pizza ordering page at _pizza.***.de_ (taken down for a while now). This should be replicated with chakra-ui components for the new consolidated Admin Lab dashboard.

**Comment by 3x071c** [comment]
@Flosi23 @IchhabLTE What's the status on this? The [pizza](https://github.com/3x071c/lsg/tree/pizza) branch has been dead for over a month (I suppose it can be deleted). There's a more recent [pizzaNew](https://github.com/3x071c/lsg/tree/pizzaNew) branch, but no associated PR? Is it ready yet?

**Comment by simonwkla** [comment]
Im currently working on it. Its not ready yet.

**Comment by 3x071c** [comment]
Closed in #262
