### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by 3x071c** [3x071c/lsg-remix#49]
Currently, we're maintaining the entire source code in English, but the actual website content is German, which I think is semantically less than ideal. We should implement internationalization according to the [Next.js docs](https://nextjs.org/docs/advanced-features/i18n-routing), with German as the primary language and English as a backup for international visitors.

**Comment by 3x071c** [comment]
Currently scheduling for M2 as I'd like to have this finished before production, I'd be open to move this to M3 if nobody deems it important enough.

**Comment by simonwkla** [comment]
I'd certainly do this after the release since 99% of all visitors are german and this feature is not essential.

**Comment by 3x071c** [comment]
Let's close this, doesn't look like something relevant for the next couple months
