### ISSUE TITLE
Restrict access when querying users

### ISSUE THREAD

**Issue by simonwkla** [3x071c/lsg-remix#62]
I would restrict access when querying users to only allow users one can edit or oneself to be queried. I will implement this in the same pr (#46) as the user and pages mutations if you dont mind.

**Comment by 3x071c** [comment]
I think this belongs in M2, since it isn't a breaking bug or security issue that requires immediate action

**Comment by simonwkla** [comment]
Ah yeah you are right. I've already implemented this though in #46 though

**Comment by 3x071c** [comment]
Closed by #46
