### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by simonwkla** [3x071c/lsg-remix#63]
Currently there seems to be no way to validate user input using nexus or prisma. What is the plan here? Should we use a library like `yup` or implement it on our own? @3x071c

**Comment by simonwkla** [comment]
I am the opinion that we should implement this on our own. Here is why:
- using a library would result in having write more code than neccessary (because every validation library requires you to have a schema)
- We already have type checking provided by nexus and that means that we usually just want to check one or two attributes, no need to use a schema for that
- We rarely have to check for correct user input. I can only think of a few occasions: passwords, usernames 
- No extra dependency :D ˆˆ/" 

To be concrete I'd suggest the following implementation: 
- Add a new file in `src/graphql` called `validation.ts`
- In this file i'd write all validation functions following this naming schema: `assertXY`. E.g: `assertMinLength()`
- If the "assertion" fails, an error with an error message should be thrown, nexus will handle this error and return a nice response :)

Here an example:

validation.ts:
```ts
export function assertMinLength(
	string: string | null | undefined,
	len: number,
	prop = "string",
): void {
	if (string != null && string.length < len) {
		throw new Error(`${prop} must be at least ${len} character(s) long`);
	}
}
```

User.ts (in the resolve function)
```ts
assertMinLength(firstname, 1, "firstname");
```

If `firstname` was an empty string, this would be the response

<img width="874" alt="image" src="https://user-images.githubusercontent.com/56218180/153947474-4f9d9a01-29ee-4941-825c-d846409b785b.png">

As you can see, we get a comprehensive error message with minimal code :D

**Comment by 3x071c** [comment]
> Should we use a library like `yup` or implement it on our own? @3x071c

Take a look [here](https://github.com/3x071c/lsg-stack/blob/54ccde40535e061ba761732438b095276ac40903/package.json#L116) 👀

> nexus will handle this error and return a nice response

I know this is picky, but Nexus delegates error handling to whatever GraphQL server implementation is running (since Nexus itself just generates a GraphQL.js-spec compliant schema), so really it's Apollo Server catching those error messages 🤓

**Comment by simonwkla** [comment]
Do you think its really necessary to have yup as a dependency?

**Comment by 3x071c** [comment]
Input validation will now be handled isomorphically via `zod` and [remix-validated-form](https://github.com/airjp73/remix-validated-form).
