### ISSUE TITLE
Move source code out of src

### ISSUE THREAD

**Issue by 3x071c** [3x071c/lsg-remix#71]
Currently, all source code is nested in `src/`, which might make scrolling the file tree on GitHub faster, but makes file paths longer and convolutes the folder structure. I'd vote for getting rid of it (see #72)

**Comment by simonwkla** [comment]
I'm fine with getting rid of this folder structure

**Comment by simonwkla** [comment]
If we change the folder structure before merging #46 though, it would make merging #46 into trunk a lot harder
